server:
  port: 8088
  servlet:
    context-path: /yoo-boot
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name} false
spring:
  jackson:
    serialization:
      indent_output: true